---------------------------Operation_log ----------------------------
CREATE TABLE IF NOT EXISTS Operation_log(
   ID INTEGER PRIMARY KEY AUTOINCREMENT,
   USER_NAME TEXT   NOT NULL,
   TENANT_NAME TEXT NOT NULL,
   SOURCE_INSTANCE  TEXT NOT NULL,
   SOURCE_SCHEMA    TEXT,
   SOURCE_TABLE     TEXT,
   DB_TYPE TEXT,
   OPERATE_TYPE,
   MESSAGE TEXT,
   OPERATION_TIME INTEGER
);